### ISSUE TITLE
recall

### ISSUE THREAD

**Issue by kallmesid** [238SAMIxD/discord-ai-bot#12]
whenever a conversation is started it mentions that we can clear using "@bot.clear" . This seems to trigger the bot again and it generated the summary of the previous response.
![Screenshot 2024-01-09 175445](https://github.com/mekb-turtle/discord-ai-bot/assets/140259324/4125a48f-0be7-4230-8efc-a97ad3e0c89a)

**Comment by sophuric** [comment]
already fixed, please update your repository version, if you have cloned with git, run `git pull`
