### ISSUE TITLE
custom SYSTEM message getting added to end of bot responses

### ISSUE THREAD

**Issue by ootagoo** [238SAMIxD/discord-ai-bot#15]
**Describe the bug**
If you change SYSTEM string message in the .env file, it will add that string to the end of a response in discord after a couple prompts with the bot.

**To Reproduce**
-in .env change SYSTEM="you are a cat that likes fish"
-On discord @bot with question. It will respond appropriately as of it were a cat as expected.
-After 2nd or 3rd interaction the bot will start adding system string to end of its responses 

Example:
User: "@catbot what are you"
Catbot: "I am a cat, meow.you are a cat that likes fish"

**Expected behavior**
Bot doesn't add system string to end of responses

**Device**
 - OS: windows 11

**Additional context**

**Comment by ootagoo** [comment]
I miss clicked and accidentally saved without adding the full title. Should say "system message keeps popping up in responses from bot"

**Comment by ootagoo** [comment]
It turns out it was the model I was using and not this code (llama2-uncensored). Switching models fixed the issue.

**Comment by sophuric** [comment]
what model were you using?

**Comment by ootagoo** [comment]
> what model were you using?

Well now im not sure if it is this code or not. i have tried a few different models and all are pulling random stuff from the SYSTEM string. Originally when posting i was using llama2-uncensored. i tried with wizard-vicuna-uncensored and it would spit out the entire system string after a couple prompts and start stacking it at the end of every reply after that. I have switched to gdisney/orca2-uncensored and now after a few prompts it will just spit out the word "system" at the end of every response. When I start the AI from a CLI and chat with it, it doesnt add anything to the end of the responses. only when i run the discord integration. Ive tried both setting the system in the model itself and through the .env and changing the respective settings in the .env but both give me the same outcome
![Screenshot 2024-03-16 012216](https://github.com/mekb-turtle/discord-ai-bot/assets/24591618/15e8523c-7aa7-4337-8846-fff4a28e51ae)
![Screenshot 2024-03-16 012040](https://github.com/mekb-turtle/discord-ai-bot/assets/24591618/821ffe78-59e6-4927-8663-d9bd2123762e)

**Comment by sophuric** [comment]
i'm getting the same issue with llama2-uncensored, however llama2 does not have this issue, i think uncensored models may not handle system messages quite well, running llama2-uncensored with `ollama run` spits out random crap most of the time so yeah
