### ISSUE TITLE
The bot won’t send messages when using WSL

### ISSUE THREAD

**Issue by hermitbernard** [238SAMIxD/discord-ai-bot#18]
**Describe the bug**
Everything works perfectly, but for some reason it does not send requests from discord channel when running ollama and discord-ai-bot from wsl

**To Reproduce**
- run ollama serve in wsl
- Verify that it correctly receives get requests when browsing to the right address
- Run discord-ai-bot from wsl
- Try to send message from discord channel 
- No request is made through the bot

**Expected behavior**
Using the same token and files when running not in WSL works flawlessly

**Device**
 - OS: Windows/WSL

**Comment by hermitbernard** [comment]
It actually gets a 404 from Ollama API on POST, therefore it’s an issue with Ollama, not the bot

**Comment by sophuric** [comment]
i haven't used WSL much, but make sure it can access the Ollama port on the host if it's running on the host. Node.js works on Windows so the Discord bot should work on Windows natively though

**Comment by hermitbernard** [comment]
Thanks for your response. I found this indeed, but haven’t had time to try the solution yet https://github.com/ollama/ollama/issues/1431

**Comment by hermitbernard** [comment]
Ok so, instead of trying the solution previously posted here https://github.com/ollama/ollama/issues/1431, I did something improbable and it worked.

it’s a known issue with ollama that when you try ollama:serve, it gives error: listen tcp 127.0.0.1:11434: bind: address already in use.

Usually to fix this issue, you need to stop the ollama.service with systemctl, then ollama serve will work as expected.

However if I do this, then the bot manages to hit / but it gets 404 from /api/generate.

Since the problem is that ollama is already running, i tried ti simply use the bot without ever launching ollama (which for some reason is already running anyway) and that worked.

I manage to post and get responses, even better, I can use ollama from the machine where it’s running, and at the same time from the bot, and those will be treated as 2 separate sessions.

It’s weird, but it works.

**Comment by sophuric** [comment]
this seems more of a ollama issue, i didn't realise it had a systemd service, but glad that you got it working!
