### ISSUE TITLE
how would i run this without the need for mentions?

### ISSUE THREAD

**Issue by DarkSeplep** [238SAMIxD/discord-ai-bot#5]
sorry for the question i know its probably a simple solution but i really have no clue where to start with this discord api.
but i would like to run it in discord chat freely so it can reply to all the messages given.

is this possible?

**Comment by sophuric** [comment]
You can use the bot in DMs, or [you can apply this patch](https://gist.githubusercontent.com/mekb-turtle/f466dd141c7a3ec6fa6089657c112af8/raw/a599dc5c353aa7f9af1ebe9dbd8a61a79775f8ae/no_mentions.patch) (download the file to the repository and run `git apply no_mentions.patch`)

**Comment by DarkSeplep** [comment]
Thank you very much.

**Comment by ToeiRei** [comment]
This would make a nice flag for the .env like NEEDS_MENTION!

**Comment by sophuric** [comment]
> NEEDS_MENTION

good idea! i'll get to work on this soon
